packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': ^1.10.0
  '@orpc/contract': ^1.11.3
  '@orpc/nest': ^1.10.2
  '@orpc/openapi': 1.10.2
  '@orpc/server': ^1.10.0
  '@orpc/zod': 1.10.2
  '@prisma/client': ^6.15.0
  '@types/express': ^5.0.1
  '@types/node': ^22.13.11
  better-auth: ^1.3.28
  dotenv: ^17.2.2
  tsdown: ^0.15.5
  typescript: ^5.8.2
  zod: ^4.1.11
