/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppMyArticlesIndexRouteImport } from './routes/_app/my-articles/index'
import { Route as AppArticlesIndexRouteImport } from './routes/_app/articles/index'
import { Route as AppMyArticlesAddRouteImport } from './routes/_app/my-articles/add'
import { Route as AppArticlesArticleIdRouteImport } from './routes/_app/articles/$articleId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppMyArticlesIndexRoute = AppMyArticlesIndexRouteImport.update({
  id: '/my-articles/',
  path: '/my-articles/',
  getParentRoute: () => AppRoute,
} as any)
const AppArticlesIndexRoute = AppArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AppRoute,
} as any)
const AppMyArticlesAddRoute = AppMyArticlesAddRouteImport.update({
  id: '/my-articles/add',
  path: '/my-articles/add',
  getParentRoute: () => AppRoute,
} as any)
const AppArticlesArticleIdRoute = AppArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/articles/$articleId': typeof AppArticlesArticleIdRoute
  '/my-articles/add': typeof AppMyArticlesAddRoute
  '/articles': typeof AppArticlesIndexRoute
  '/my-articles': typeof AppMyArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/articles/$articleId': typeof AppArticlesArticleIdRoute
  '/my-articles/add': typeof AppMyArticlesAddRoute
  '/articles': typeof AppArticlesIndexRoute
  '/my-articles': typeof AppMyArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/articles/$articleId': typeof AppArticlesArticleIdRoute
  '/_app/my-articles/add': typeof AppMyArticlesAddRoute
  '/_app/articles/': typeof AppArticlesIndexRoute
  '/_app/my-articles/': typeof AppMyArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/'
    | '/articles/$articleId'
    | '/my-articles/add'
    | '/articles'
    | '/my-articles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/'
    | '/articles/$articleId'
    | '/my-articles/add'
    | '/articles'
    | '/my-articles'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/'
    | '/_app/articles/$articleId'
    | '/_app/my-articles/add'
    | '/_app/articles/'
    | '/_app/my-articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/my-articles/': {
      id: '/_app/my-articles/'
      path: '/my-articles'
      fullPath: '/my-articles'
      preLoaderRoute: typeof AppMyArticlesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/articles/': {
      id: '/_app/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AppArticlesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-articles/add': {
      id: '/_app/my-articles/add'
      path: '/my-articles/add'
      fullPath: '/my-articles/add'
      preLoaderRoute: typeof AppMyArticlesAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/articles/$articleId': {
      id: '/_app/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof AppArticlesArticleIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppArticlesArticleIdRoute: typeof AppArticlesArticleIdRoute
  AppMyArticlesAddRoute: typeof AppMyArticlesAddRoute
  AppArticlesIndexRoute: typeof AppArticlesIndexRoute
  AppMyArticlesIndexRoute: typeof AppMyArticlesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppArticlesArticleIdRoute: AppArticlesArticleIdRoute,
  AppMyArticlesAddRoute: AppMyArticlesAddRoute,
  AppArticlesIndexRoute: AppArticlesIndexRoute,
  AppMyArticlesIndexRoute: AppMyArticlesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
