name: Deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - app: backend
            context: apps/backend
            dockerfile: apps/backend/Dockerfile
            image_suffix: -backend
          - app: website
            context: apps/website
            dockerfile: apps/website/Dockerfile
            image_suffix: -website

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}${{ matrix.image_suffix }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_NAME=${{ matrix.app }}
            INFISICAL_MACHINE_CLIENT_ID=${{ secrets.INFISICAL_MACHINE_CLIENT_ID }}
            INFISICAL_MACHINE_CLIENT_SECRET=${{ secrets.INFISICAL_MACHINE_CLIENT_SECRET }}
            INFISICAL_SECRET_ENV=${{ secrets.INFISICAL_SECRET_ENV }}
            INFISICAL_API_URL=${{ secrets.INFISICAL_API_URL }}
            INFISICAL_SECRET_ENV=${{ secrets.INFISICAL_SECRET_ENV }}
            INFISICAL_PROJECT_ID=${{ secrets.INFISICAL_PROJECT_ID }}
